name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Frontend Tests & Build
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: |
        # Install ESLint if not present
        if [ ! -f package.json ] || ! grep -q "eslint" package.json; then
          echo "No ESLint configured, skipping..."
        else
          npm run lint
        fi
    
    - name: Run tests
      run: |
        # Run tests if test script exists
        if [ -f package.json ] && grep -q "test" package.json; then
          npm test
        else
          echo "No tests configured, skipping..."
        fi
    
    - name: Build check
      run: |
        # Check if files are valid
        echo "Checking HTML files..."
        find . -name "*.html" -exec echo "Validating {}" \;
        
        echo "Checking CSS files..."
        find . -name "*.css" -exec echo "Validating {}" \;
        
        echo "Checking JavaScript files..."
        find . -name "*.js" -exec node -c {} \;

  # Backend Tests & Build
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'rahla-api/package-lock.json'
    
    - name: Install backend dependencies
      working-directory: ./rahla-api
      run: npm ci
    
    - name: Run backend linting
      working-directory: ./rahla-api
      run: |
        if [ ! -f package.json ] || ! grep -q "eslint" package.json; then
          echo "No ESLint configured, skipping..."
        else
          npm run lint
        fi
    
    - name: Run backend tests
      working-directory: ./rahla-api
      run: |
        if [ -f package.json ] && grep -q "test" package.json; then
          npm test
        else
          echo "No tests configured, skipping..."
        fi
    
    - name: Check backend syntax
      working-directory: ./rahla-api
      run: |
        echo "Checking JavaScript syntax..."
        find src -name "*.js" -exec node -c {} \;

  # Security Scan
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        if [ -f package.json ]; then
          npm audit --audit-level moderate
        fi
        
        if [ -f rahla-api/package.json ]; then
          cd rahla-api
          npm audit --audit-level moderate
        fi
    
    - name: Check for secrets
      run: |
        # Check for potential secrets in code
        if grep -r "password\|secret\|key" . --include="*.js" --include="*.json" | grep -v node_modules | grep -v ".git"; then
          echo "Warning: Potential secrets found in code"
        else
          echo "No obvious secrets found"
        fi

  # Deploy to Render (only on main branch)
  deploy:
    needs: [frontend, backend, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
    
    - name: Notify deployment
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "Frontend: https://bthwani1.github.io/web-test"
        echo "Backend: Check Render dashboard for URL"
