name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security scan
        run: |
          echo "Running security checks..."
          # Add gitleaks, trufflehog, or other security tools here
          echo "Security scan completed"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd rahla-api
          npm ci
      - name: Run tests
        run: |
          cd rahla-api
          npm test
      - name: Check coverage
        run: |
          echo "Coverage check would go here"
          # Add coverage threshold check

  build:
    runs-on: ubuntu-latest
    needs: [security-scan, test]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          echo "Build completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        run: |
          echo "Deployment to Render would go here"
          # Add Render deployment step
